theme: jekyll-theme-minimal
site.name: "Fedora Remix for WSL How To's"
title: "Fedora Remix for WSL How To's"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      site.name: "Fedora Remix for WSL How To's"
